version: '3.8'

services:
  vector-db-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vector-db-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - PORT=8000
    volumes:
      # Mount source code for development (optional)
      - ./src:/app/src:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vector-db-network

networks:
  vector-db-network:
    driver: bridge

volumes:
  # Add persistent volumes if needed for data storage
  vector-db-data:
