from typing import List, Tuple
from uuid import UUID

class BaseIndex:
    def add(self, chunk_id: UUID, vec: List[float]): ...
    def update(self, chunk_id: UUID, vec: List[float]): ...
    def remove(self, chunk_id: UUID): ...
    def search(self, query: List[float], k: int = 10, metric: str = "cosine") -> List[Tuple[UUID, float]]: ...
    def rebuild(self, items: List[Tuple[UUID, List[float]]]): ...